import assert from 'node:assert/strict';
import { RECIPES, DISHES, normalizeCooking, recipeQuote, learnRecipe, upgradeRecipe } from '../src/cooking.js';
import { cookMeal, eatMeal, freshState, normalizeState, moveStock, catchSeafood } from '../src/economy.js';
import { getInventoryRows, inventoryAction } from '../src/inventoryUi.js';
import { COOKING_MOBILE_HEIGHT, drawCookingPanel, drawDishIcon } from '../src/cookingUi.js';

const state = freshState(0);
assert.equal(Object.keys(RECIPES).length, 8);
assert.equal(state.cooking.bakedPotato.level, 1);
assert.equal(state.cooking.gardenSoup.level, 0);
assert.equal(recipeQuote(state, 'missing').reason, 'invalid-recipe');
assert.equal(cookMeal(state, 'gardenSoup').reason, 'locked');
const before = structuredClone(state);
assert.equal(cookMeal(state, 'bakedPotato').reason, 'ingredients');
assert.deepEqual(state, before);
state.inventory = { sweetPotato: 20 }; state.stamina = 12; state.satiety = 10;
const clock = state.gameMinutes;
const first = cookMeal(state, 'bakedPotato');
assert.equal(first.ok, true);
assert.equal(state.inventory.sweetPotato, 19);
assert.equal(state.inventory[first.itemId], 1);
assert.equal(state.stamina, 12); assert.equal(state.satiety, 10);
assert.equal(state.gameMinutes, clock); // Crafting must never jump the game clock.
assert.equal(Object.values(state.inventory).reduce((a, b) => a + b, 0), 20);
assert.equal(upgradeRecipe(state, 'bakedPotato').reason, 'practice');
cookMeal(state, 'bakedPotato'); cookMeal(state, 'bakedPotato');
assert.equal(upgradeRecipe(state, 'bakedPotato').level, 2);
const second = cookMeal(state, 'bakedPotato');
assert.equal(second.dish.satiety, 52);
assert.equal(DISHES[first.itemId].satiety, 42);
assert.equal(eatMeal(state, first.itemId).satiety, 52);
assert.equal(eatMeal(state, second.itemId).satiety, 100);
assert.equal(state.stamina, 12);
const full = structuredClone(state);
assert.equal(eatMeal(state).reason, 'full'); assert.deepEqual(state, full);
state.satiety = 0;
assert.equal(eatMeal(state, 'meal_bakedPotato_3').reason, 'no-food');
assert.equal(state.satiety, 0); // An unavailable selection cannot consume another item.
state.gold = 100;
assert.equal(learnRecipe(state, 'gardenSoup').ok, true);
assert.equal(state.gold, 85);
assert.equal(learnRecipe(state, 'gardenSoup').reason, 'known');
state.inventory = { tomato: 1 };
const insufficient = structuredClone(state);
assert.equal(cookMeal(state, 'gardenSoup').reason, 'ingredients'); assert.deepEqual(state, insufficient);
state.inventory.pumpkin = 1;
assert.equal(cookMeal(state, 'gardenSoup').dish.satiety, 72);
assert.deepEqual(state.inventory, { meal_gardenSoup_1: 1 });
assert.equal(moveStock(state, 'meal_gardenSoup_1', 1).ok, true);
assert.equal(normalizeState(JSON.parse(JSON.stringify(state))).storage.meal_gardenSoup_1, 1);
assert.equal(moveStock(state, 'meal_gardenSoup_1', 1, 'storage', 'inventory').ok, true);
const row = getInventoryRows(state, 'bag')[0];
assert.equal(row.kind, 'meal'); assert.equal(row.level, 1); assert.match(row.summary, /72/);
assert.equal(inventoryAction(row.id, 'bag').id, `inventory-use:${row.id}`);
const fish = freshState(0); fish.rodLevel = 2;
catchSeafood(fish, 'reefFish', 'rod', () => .01);
learnRecipe(fish, 'reefGrill');
assert.equal(cookMeal(fish, 'reefGrill').ok, true);
assert.equal(fish.fishCount, 0); assert.equal(fish.fishValue, 0);
const saved = normalizeState({ ...state, cooking: { bakedPotato: { level: 999, cooked: -5 }, gardenSoup: { level: 2, cooked: 9 }, invalid: { level: 3 } } });
assert.deepEqual(saved.cooking.bakedPotato, { level: 3, cooked: 0 });
assert.equal(saved.cooking.gardenSoup.level, 2); assert.equal(saved.cooking.invalid, undefined);
assert.deepEqual(normalizeState({ schemaVersion: 2 }).cooking, normalizeCooking(null));
const chef = freshState(0); chef.gold = 999; chef.inventory = { corn: 10 };
for (let i = 0; i < 3; i++) cookMeal(chef, 'grilledCorn');
assert.equal(upgradeRecipe(chef, 'grilledCorn').level, 2);
assert.equal(upgradeRecipe(chef, 'grilledCorn').reason, 'practice');
for (let i = 0; i < 5; i++) cookMeal(chef, 'grilledCorn');
assert.equal(upgradeRecipe(chef, 'grilledCorn').level, 3);
assert.equal(upgradeRecipe(chef, 'grilledCorn').reason, 'max-level');
assert.equal(normalizeState(chef).inventory.meal_grilledCorn_2, 5);
const poor = freshState(0); poor.gold = 0;
assert.equal(learnRecipe(poor, 'crabStew').reason, 'gold');
poor.cooking.bakedPotato.cooked = 3;
assert.equal(upgradeRecipe(poor, 'bakedPotato').reason, 'gold');
const overflowing = freshState(0); overflowing.inventory = { corn: 1, sweetPotatoSeed: 20 };
assert.equal(cookMeal(overflowing, 'grilledCorn').reason, 'capacity');
const texts = [];
const ctx = new Proxy({ fillText: (text) => texts.push(text) }, { get: (target, key) => target[key] ?? (() => {}) });
for (const narrow of [false, true]) {
  const buttons = drawCookingPanel(ctx, chef, { selectedId: 'bakedPotato', narrow, offset: 0, labels: { sweetPotato: '地瓜' } });
  assert.equal(buttons.length, narrow ? 9 : 11);
  for (const b of buttons) assert.ok(b.x >= 0 && b.x + b.width <= 1024 && b.y + b.height <= (narrow ? COOKING_MOBILE_HEIGHT : 740));
  for (const recipe of Object.values(RECIPES)) drawDishIcon(ctx, recipe, 0, 0, 80);
}
assert.ok(texts.some((text) => text.includes('升级')));
console.log('cooking: recipes, ingredients, upgrades, nutrition, saves and responsive UI passed');
