import assert from 'node:assert/strict';
import { CROPS } from '../src/economy.js';
import { plotGuidance, nextPlayerAction, voyageSupplies } from '../src/playerGuidance.js';

const state = { gameMinutes: 100, satiety: 70, stamina: 60, inventory: { sweetPotatoSeed: 2 }, freshwater: { canteen: 2 }, boatDurability: 80, boatTier: 'wood', plots: [] };
const plot = { id: 'p1', crop: { id: 'sweetPotato', growthMinutes: 10, wateredUntil: 99 } };
state.plots = [plot];
assert.equal(plotGuidance(state, plot).action, '浇水');
assert.match(plotGuidance(state, plot).detail, /缺水暂停/);
assert.equal(nextPlayerAction(state).page, 'farm');
state.freshwater.canteen = 0;
assert.equal(nextPlayerAction(state).page, 'water');
plot.crop.wateredUntil = 1000;
assert.equal(plotGuidance(state, plot).action, '查看生长');
assert.match(plotGuidance(state, plot).detail, new RegExp(`${CROPS.sweetPotato.minutes - 10} 游戏分钟`));
plot.pauseUntil = 130;
assert.match(plotGuidance(state, plot).detail, /受灾停长还剩 30 分钟/);
plot.crop.growthMinutes = CROPS.sweetPotato.minutes;
assert.equal(plotGuidance(state, plot).action, '收获');
assert.equal(nextPlayerAction(state).plotId, plot.id);
plot.crop = null;
assert.equal(plotGuidance(state, plot).action, '播种');
state.inventory = { palmSeed: 5 };
assert.equal(plotGuidance(state, plot).action, '购买种子');
assert.equal(voyageSupplies(state).food, 0);
state.inventory = { sweetPotato: 3, sweetPotatoSeed: 10, shells: 20 };
assert.equal(voyageSupplies(state).food, 3);
state.boatDurability = 0;
assert.match(voyageSupplies(state).advice, /修船/);
state.satiety = 10;
assert.equal(nextPlayerAction(state).page, 'inventory');
console.log('Player guidance tests passed');
